E1024 09:27:16.913589 1058589 dev.go:79] Failed to load initial config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:27:16.917623 1058589 watch.go:102] watchAllDir unable to walk dir `/home/htoo-myat-eain/amk/driving_app/dataconnect`: lstat /home/htoo-myat-eain/amk/driving_app/dataconnect: no such file or directory
I1024 09:27:16.918028 1058589 dev.go:102] Listening on address (HTTP + gRPC): 127.0.0.1:50001
E1024 09:27:26.925035 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:27:36.926511 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:27:46.918792 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:27:56.927498 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:28:06.918102 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:28:16.918807 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:28:26.926673 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:28:36.927561 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:28:46.918764 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:28:56.931194 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:29:07.099076 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:29:17.167775 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:29:17.371138 1058589 watch.go:102] watchAllDir unable to walk dir `/home/htoo-myat-eain/amk/driving_app/dataconnect`: lstat /home/htoo-myat-eain/amk/driving_app/dataconnect: no such file or directory
E1024 09:29:26.966477 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:29:37.143743 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:29:47.794328 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:29:57.201359 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:30:07.202602 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:30:17.154706 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:30:27.062669 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:30:36.964916 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:30:46.965729 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:30:56.952457 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:31:06.958305 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:31:16.962883 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:31:16.975725 1058589 watch.go:102] watchAllDir unable to walk dir `/home/htoo-myat-eain/amk/driving_app/dataconnect`: lstat /home/htoo-myat-eain/amk/driving_app/dataconnect: no such file or directory
E1024 09:31:26.928740 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:31:36.939641 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:31:46.918775 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:31:56.927463 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:32:06.956220 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:32:16.927443 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:32:26.933766 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:32:36.932198 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:32:46.931612 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:32:56.918620 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:33:06.926624 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:33:16.919908 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:33:16.919957 1058589 watch.go:102] watchAllDir unable to walk dir `/home/htoo-myat-eain/amk/driving_app/dataconnect`: lstat /home/htoo-myat-eain/amk/driving_app/dataconnect: no such file or directory
E1024 09:33:26.926600 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:33:36.928534 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:33:46.918916 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:33:56.927236 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:34:06.927426 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:34:16.933758 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:34:26.930517 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:34:36.927955 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:34:46.918771 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:34:56.927975 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:35:06.928275 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:35:16.920688 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:35:16.921585 1058589 watch.go:102] watchAllDir unable to walk dir `/home/htoo-myat-eain/amk/driving_app/dataconnect`: lstat /home/htoo-myat-eain/amk/driving_app/dataconnect: no such file or directory
E1024 09:35:26.926706 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:35:36.927619 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:35:46.926014 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:35:56.918151 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:36:06.927654 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:36:16.918735 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:36:26.927463 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:36:36.931682 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:36:47.464462 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:36:57.242834 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:37:07.142645 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:37:17.123827 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:37:17.194163 1058589 watch.go:102] watchAllDir unable to walk dir `/home/htoo-myat-eain/amk/driving_app/dataconnect`: lstat /home/htoo-myat-eain/amk/driving_app/dataconnect: no such file or directory
E1024 09:37:27.114488 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:37:37.009070 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:37:46.978600 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:37:56.987538 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:38:06.995247 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:38:16.958240 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:38:27.084595 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:38:37.907024 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:38:48.241805 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:38:56.956328 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:39:06.918041 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:39:16.919314 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:39:16.919374 1058589 watch.go:102] watchAllDir unable to walk dir `/home/htoo-myat-eain/amk/driving_app/dataconnect`: lstat /home/htoo-myat-eain/amk/driving_app/dataconnect: no such file or directory
E1024 09:39:26.927497 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:39:36.949363 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:39:46.918655 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:39:56.960638 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:40:06.942605 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:40:16.936464 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:40:26.918559 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:40:36.935407 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:40:46.920230 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:40:56.926553 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:41:06.927612 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:41:16.918652 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:41:16.918688 1058589 watch.go:102] watchAllDir unable to walk dir `/home/htoo-myat-eain/amk/driving_app/dataconnect`: lstat /home/htoo-myat-eain/amk/driving_app/dataconnect: no such file or directory
E1024 09:41:26.927298 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:41:36.926928 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:41:46.919610 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:41:56.927885 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:42:06.918354 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:42:16.919047 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:42:26.926508 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:42:36.927500 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:42:46.918683 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:42:56.926557 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:43:06.927587 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:43:16.918862 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:43:16.918957 1058589 watch.go:102] watchAllDir unable to walk dir `/home/htoo-myat-eain/amk/driving_app/dataconnect`: lstat /home/htoo-myat-eain/amk/driving_app/dataconnect: no such file or directory
E1024 09:43:26.927442 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:43:36.928022 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:43:46.919565 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:43:56.928417 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:44:06.927527 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
E1024 09:44:16.926597 1058589 watch.go:31] Failed to load config from "/home/htoo-myat-eain/amk/driving_app/dataconnect": could not find dataconnect.yaml in `/home/htoo-myat-eain/amk/driving_app/dataconnect`
